### ISSUE TITLE
src/download_images.py cannot find file

### ISSUE THREAD

**Issue by PragyanSubedi** [Neilblaze/Map-Path-Segmentation#2]
Looks like the folder and file where `download_images.py` looks for the `Images.txt` isn't present. Could you please add that in @Neilblaze?

```
$ python download_images.py
Traceback (most recent call last):
  File "D:\Youtube\Satellite Aerial Image Classification and Segmentation\Map-Path-Segmentation\src\download_images.py", line 33, in <module>
    download_images(type, mode, url_file_path, output_file_root)
  File "D:\Youtube\Satellite Aerial Image Classification and Segmentation\Map-Path-Segmentation\src\download_images.py", line 17, in download_images
    with open(url_file_path, 'r') as link_file:
FileNotFoundError: [Errno 2] No such file or directory: '../Data/Roads/_Links/Images.txt'
```

**Comment by aarav2you** [comment]
The repository is clearly copied and is missing the original files that make it unable to function. The aforementioned "Indian roads dataset" also does not exist.
https://github.com/Neilblaze/Map-Path-Segmentation/commit/235500127bf2b64884d91649ccc2cfa94a390e6a
https://github.com/Paulymorphous/skeyenet

**Comment by chinmay3** [comment]
any updates to this?

**Comment by Neilblaze** [comment]
> any updates to this?

Replied on #3 , thanks!
